name: Deploy PRODUCTION
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m

          script: |
            cd /var/www
            cd microapp.partners.kawa.ng/api
            git fetch --all
            git pull origin main
            echo 'Updates successfully pulled from DEV branch'
            sudo docker compose up --build -d --force-recreate
            echo 'Build successfully completed'

  internal_health_check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Sleep for 80 Secs and Test Urls
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            sleep 80

            echo 'Slept for 80 seconds'

            # curl http://localhost:8842/health-check

      - name: Send curl request to homepage URL
        run: |
          # curl  http://microapp.partners.kawa.ng/health